### ISSUE TITLE
unbalanced designs

### ISSUE THREAD

**Issue by vogab** [hyemin-han/BayesFMRI#3]
Hi,
I was wondering if this program can be used to run 2nd level analyses on fmri data with unbalanced designs? In the tutorial, it seems that you make the contrast within subject, and then test if the value in each voxel is e.g. >0 at the group level.

However, I am in a situation in which each subject has not been exposed to all the conditions. I have 34 Ss for Condition 1, and 50 for Condition 2. So, I cannot make a within subject contrast and follow the same procedure described in the tutorial with my own data, it seems.

So, I think that what I would need is being able to feed the data for Condition 1 and for Condition 2, and contrast them at the 2nd level between subject. Do you think that it would be possible to conduct such an analysis with BayesFactorFMRI?

**Comment by hyemin-han** [comment]
Unfortunately, BayesFactorFMRI with GUI is not capable of doing the two-group t-test. Instead, if you are comfortable with doing some coding stuff, you may consider trying this, a variation of BayesFactorFMRI that I composed:

[https://github.com/hyemin-han/BayesFactorFMRI_TWOT](https://github.com/hyemin-han/BayesFactorFMRI_TWOT)

If you intend to use this tool for publication, please cite these two papers:

Han, H. (2020). Implementation of Bayesian multiple comparison correction in the second-level analysis of fMRI data: With pilot analyses of simulation and real fMRI datasets based on voxelwise inference. _Cognitive neuroscience, 11_(3), 157-169. https://doi.org/10.1080/17588928.2019.1700222
Han, H. (2021). BayesFactorFMRI: Implementing Bayesian Second-Level fMRI Analysis with Multiple Comparison Correction and Bayesian Meta-Analysis of fMRI Images with Multiprocessing. _Journal of Open Research Software, 9_(1), 1. https://doi.org/10.5334/jors.328

**Comment by vogab** [comment]
looks like what I need thanks!!!

**Comment by hyemin-han** [comment]
Thanks, I will close the current issue.
