### ISSUE TITLE
Multiple-comparison correction of the Cauchy scale

### ISSUE THREAD

**Issue by julienbesle** [hyemin-han/BayesFMRI#4]
Hi Hyemin,

First, thanks for making this software available. 
I have a question specifically about your implementation of the Westfall/Jeffrey's multiple-comparison correction procedure, described in your 2020 Cognitive Neuroscience paper (as implemented in correct_scale.R). 
You've chosen to correct for the number of "conditions" (m) that would result in a number of pairwise comparisons (k) greater or equal to the number of voxelwise tests. In Westfall et al. (1997), as described in de Jong et al. (2019), this is justified by the fact that they're actually correcting across pairwise comparisons of levels within a factor. But in the case of mass-univariate tests, how do we justify this? In other words, how do we know that the dependence structure of the data across voxels is analogous to that of all pairwise comparisons of levels within a factor? Shouldn't you be using the number of voxels instead of m, and do the rescaling using 1-alpha^(1/n_voxels), as in Jeffreys (1938), instead of (1 - alpha^(2/m)) as in Westfall et al. (1997)?
I guess this would make the correction too conservative?

Thanks!
Julien

**Comment by hyemin-han** [comment]
Hi Julien,

Thank you very much for your interest in my program. That is a great question indeed. Yes, you were correct regarding the point that use of 1-alpha^(1/n_voxels) is likely to be conservative. Doing so will result in Bonferroni correction, so I calculated a hypothetical m number to conduct a more lenient correction as mentioned in de Jong. Of course, if you want to try, please feel free to modify the part dealing with correction in my code. That is completely fine provided that you cite my paper(s) accordingly. Again, thank you very much for your interest and question. Good luck with your research project!

Thanks,
Hyemin
